

name: Build_Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  

jobs:
  build_test:

    runs-on: ubuntu-latest


    steps:
    - name: Clone repo
      uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install dependencies    
      run: npm install
    - name: Run unit tests
      run: npm run test:unit
    - name: Display SoftUni username
      run: echo "savinabg"


  ui-tests:
    
    runs-on: ubuntu-latest
    needs: build_test

    steps:
    - name: Clone repo
      uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install dependencies    
      run: npm install
    - name: Start the app
      run: npm run start &
    - name: Install Playwright browser
      run: npx playwright install
    - name: Run UI tests
      run: npm run test:ui    